[build]
  command = "npm run build"
  publish = "_site"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "npm run start"
  targetPort = 8080
  port = 8888